#!/usr/bin/env python3
"""Regenerate datasets/cry-detect-01/INVENTORY.md.

Quick-reference single-page snapshot of:
  - dataset size by date / quality tier
  - sub-type breakdown of cries
  - environmental skew of negatives
  - time-of-day distribution
  - firmware-era split

Re-run after every audit to refresh. Deterministic from master.csv.

Usage:  tools/build_inventory.py
"""
from __future__ import annotations

import csv
import datetime as dt
import subprocess
from collections import Counter, defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
DATASET = REPO / "datasets" / "cry-detect-01"
MASTER  = DATASET / "labels" / "master.csv"
OUT     = DATASET / "INVENTORY.md"


def git_head_sha():
    try:
        return subprocess.check_output(
            ["git", "-C", str(REPO), "rev-parse", "--short", "HEAD"],
            stderr=subprocess.DEVNULL).decode().strip()
    except Exception:
        return "unknown"


def sha256_short(path, n=12):
    """Short sha256 prefix of a file (for model identity)."""
    import hashlib
    if not Path(path).exists(): return "missing"
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while (b := f.read(1 << 20)):
            h.update(b)
    return h.hexdigest()[:n]


def probe_device_build_sha(host="http://192.168.1.100", timeout=2):
    """Live probe — returns the firmware ELF sha8 if device responds."""
    import urllib.request, json
    try:
        with urllib.request.urlopen(f"{host}/metrics", timeout=timeout) as resp:
            data = json.loads(resp.read())
            return data.get("build_sha", "unreachable"), data.get("uptime_s", 0)
    except Exception:
        return "unreachable", None


def f(s, default=0.0):
    try: return float(s) if s else default
    except Exception: return default


def main():
    if not MASTER.exists():
        print(f"master labels missing at {MASTER}; run ensemble_audit.py first")
        return 1

    rows = list(csv.DictReader(open(MASTER)))
    n = len(rows)

    # --- date × tier ---
    by_date = defaultdict(lambda: Counter())
    for r in rows:
        d = r["ts_iso"][:10] if r["ts_iso"] else "?"
        by_date[d][r["confidence_tier"]] += 1
    dates_sorted = sorted(by_date)

    # --- aggregates ---
    tier_total = Counter(r["confidence_tier"] for r in rows)

    # --- cluster within high_pos ---
    hp_clusters = Counter(r["cluster_label"] for r in rows
                          if r["confidence_tier"]=="high_pos" and r["cluster_label"])

    # --- negatives speech vs other ---
    hn_speech = sum(1 for r in rows if r["confidence_tier"]=="high_neg" and f(r["yam_speech_score"]) >= 0.5)
    hn_other  = sum(1 for r in rows if r["confidence_tier"]=="high_neg" and f(r["yam_speech_score"]) < 0.5)

    # --- session attribution ---
    sessions = sorted(set(r["session_id"] for r in rows))
    sess_info = {}
    for s in sessions:
        sr = [r for r in rows if r["session_id"] == s]
        ds = sorted(r["ts_iso"][:10] for r in sr if r["ts_iso"])
        sess_info[s] = {
            "n": len(sr),
            "span": f"{ds[0]} → {ds[-1]}" if ds else "?",
            "high_pos": sum(1 for r in sr if r["confidence_tier"]=="high_pos"),
            "high_neg": sum(1 for r in sr if r["confidence_tier"]=="high_neg"),
        }

    # --- cluster × date ---
    cdate = defaultdict(lambda: Counter())
    for r in rows:
        if r["confidence_tier"] != "high_pos" or not r["cluster_label"]: continue
        d = r["ts_iso"][:10] if r["ts_iso"] else "?"
        cdate[d][r["cluster_label"]] += 1

    # --- hour-of-day ---
    hp_hour = Counter(); hn_hour = Counter()
    for r in rows:
        if not r["ts_iso"]: continue
        try: h = int(r["ts_iso"][11:13])
        except Exception: continue
        if r["confidence_tier"]=="high_pos": hp_hour[h] += 1
        elif r["confidence_tier"]=="high_neg": hn_hour[h] += 1

    # --- firmware-era split (rough, by capture date) ---
    era_count = Counter()
    for r in rows:
        if not r["ts_iso"]: continue
        d = r["ts_iso"][:10]
        if d <= "2026-04-22": era = "broken (double-sigmoid bug)"
        elif d == "2026-04-23": era = "sigmoid-fix only"
        else: era = "mel-fix (full)"
        era_count[era] += 1

    # ---------------------------------------------------------------
    # Render
    # ---------------------------------------------------------------
    out = []
    out.append("# cry-detect-01 — data inventory")
    out.append("")
    out.append(f"_Auto-generated by `tools/build_inventory.py`. Re-run after each "
               f"ensemble_audit pass for a fresh snapshot._")
    out.append("")
    out.append(f"**Generated:** {dt.datetime.now(dt.timezone(dt.timedelta(hours=10))).isoformat(timespec='seconds')}  ")
    out.append(f"**Source:** `{MASTER.relative_to(REPO)}`  ")
    out.append(f"**Git HEAD:** `{git_head_sha()}`  ")
    out.append(f"**Total captures:** {n}  ")
    out.append("")
    if dates_sorted:
        out.append(f"**Date range:** {dates_sorted[0]} → {dates_sorted[-1]} ({len(dates_sorted)} calendar days)")
    out.append("")

    # ---------------------------------------------------------------
    # Active models — copy these into ml-experiments/<dir>/config.json
    # ---------------------------------------------------------------
    out.append("## Active models (copy into experiment `config.json`)")
    out.append("")
    deployed_tflite = REPO / "projects" / "cry-detect-01" / "spiffs" / "yamnet.tflite"
    tflite_sha = sha256_short(deployed_tflite)
    fw_sha, fw_uptime = probe_device_build_sha()
    fw_state = f"`{fw_sha}` (uptime {fw_uptime}s)" if fw_uptime else f"`{fw_sha}`"
    # Pull ensemble + yamnet oracle versions from any non-empty row
    ens_v = next((r["ensemble_version"] for r in rows if r.get("ensemble_version")), "?")
    yam_v = next((r["yamnet_oracle_version"] for r in rows if r.get("yamnet_oracle_version")), "?")
    audited = next((r["audited_at"] for r in rows if r.get("audited_at")), "?")
    out.append("| component | version / identity |")
    out.append("|---|---|")
    out.append(f"| YAMNet FP32 oracle (host) | `{yam_v}` |")
    out.append(f"| YAMNet INT8 (deployed) | `spiffs/yamnet.tflite` (sha256 `{tflite_sha}…`) |")
    out.append(f"| Firmware on device (live probe) | {fw_state} |")
    out.append(f"| Ensemble version | `{ens_v}` |")
    out.append(f"| Last ensemble audit | `{audited}` |")
    out.append(f"| Feature classifier | sklearn LogReg, retrained at audit time (seed=0) |")
    out.append(f"| Sub-type cluster | KMeans k=4, refit at audit time (seed=0) |")
    out.append("")

    # Tier totals
    out.append("## Confidence tiers")
    out.append("")
    out.append("| tier | n | meaning |")
    out.append("|---|---:|---|")
    out.append(f"| high_pos | {tier_total['high_pos']} | confident cry — training positives |")
    out.append(f"| high_neg | {tier_total['high_neg']} | confident not-cry — training negatives |")
    out.append(f"| medium_pos | {tier_total['medium_pos']} | cry-leaning, single oracle confident |")
    out.append(f"| medium_neg | {tier_total['medium_neg']} | not-cry-leaning |")
    out.append(f"| low | {tier_total['low']} | oracle disagreement (research subset) |")
    out.append(f"| **TOTAL** | **{n}** | |")
    out.append("")
    out.append(f"**Training-eligible** (`high_pos ∪ high_neg`): "
               f"**{tier_total['high_pos'] + tier_total['high_neg']}**")
    out.append("")

    # Daily breakdown
    out.append("## Captures by date × tier")
    out.append("")
    out.append("| date | high_pos | high_neg | med_pos | med_neg | low | total |")
    out.append("|---|---:|---:|---:|---:|---:|---:|")
    for d in dates_sorted:
        tc = by_date[d]; tot = sum(tc.values())
        out.append(f"| {d} | {tc['high_pos']} | {tc['high_neg']} | {tc['medium_pos']} | {tc['medium_neg']} | {tc['low']} | {tot} |")
    out.append(f"| **TOTAL** | **{tier_total['high_pos']}** | **{tier_total['high_neg']}** | "
               f"**{tier_total['medium_pos']}** | **{tier_total['medium_neg']}** | "
               f"**{tier_total['low']}** | **{n}** |")
    out.append("")

    # Sessions
    out.append("## Sessions")
    out.append("")
    out.append("| session | date span | n | high_pos | high_neg |")
    out.append("|---|---|---:|---:|---:|")
    for s in sessions:
        si = sess_info[s]
        out.append(f"| `{s}` | {si['span']} | {si['n']} | {si['high_pos']} | {si['high_neg']} |")
    out.append("")

    # Cry sub-types
    out.append("## Cry sub-types (within high_pos)")
    out.append("")
    out.append("| sub-type | n | f0_mean (cluster centroid) |")
    out.append("|---|---:|---:|")
    centroids = {"fuss": "~340 Hz", "full_cry": "~590 Hz", "distress": "~810 Hz", "screech": "~1040 Hz"}
    for c in ("full_cry","fuss","distress","screech"):
        out.append(f"| {c} | {hp_clusters[c]} | {centroids[c]} |")
    out.append("")
    if hp_clusters.get("screech", 0) < 10:
        out.append("> ⚠️ `screech` cluster is sparse (n < 10). "
                   "Don't fit a sub-type classifier on this until 30+ examples accumulate.")
        out.append("")

    # Cluster × date
    out.append("### Cry sub-type by date (high_pos)")
    out.append("")
    out.append("| date | fuss | full_cry | distress | screech | total |")
    out.append("|---|---:|---:|---:|---:|---:|")
    for d in sorted(cdate):
        c = cdate[d]
        out.append(f"| {d} | {c['fuss']} | {c['full_cry']} | {c['distress']} | {c['screech']} | {sum(c.values())} |")
    out.append("")

    # Negatives breakdown
    out.append("## Negatives (within high_neg)")
    out.append("")
    out.append("| type | n | character |")
    out.append("|---|---:|---|")
    out.append(f"| speech-dominated | {hn_speech} | yam_speech_score ≥ 0.5 — caregiver / TV / adult voice |")
    out.append(f"| silence / ambient | {hn_other} | quiet bedroom or non-voiced household noise |")
    out.append("")
    if hn_speech > 0 and hn_speech / max(hn_speech + hn_other, 1) > 0.65:
        out.append(f"> ⚠️ Negatives are **{100*hn_speech//max(hn_speech+hn_other,1)}% caregiver-speech**. "
                   "Models trained here may overlearn 'cry vs human voice' rather than "
                   "'cry vs general noise'. Mitigate with synthetic noise augmentation, "
                   "or deliberately collect more household-ambient sessions.")
        out.append("")

    # Hour-of-day
    out.append("## Time-of-day distribution (high tiers)")
    out.append("")
    out.append("| hour | high_pos | high_neg |")
    out.append("|---:|---:|---:|")
    all_hours = sorted(set(hp_hour) | set(hn_hour))
    for h in all_hours:
        hp = hp_hour[h]; hn = hn_hour[h]
        bar = "▍" * min(hp, 36)
        out.append(f"| {h:02d}h | {hp} | {hn} |")
    out.append("")

    # Firmware-era
    out.append("## Firmware era at capture time")
    out.append("")
    out.append("WAVs are immutable; YAMNet labels are firmware-independent. This split matters "
               "only for the on-device `cry_conf` field (different scales per build).")
    out.append("")
    out.append("| era | n | scale of `cry_conf` |")
    out.append("|---|---:|---|")
    eras = [
        ("broken (double-sigmoid bug)", "clipped at 0.73, unusable"),
        ("sigmoid-fix only",            "partial — mel-power bug still active"),
        ("mel-fix (full)",              "usable — matches FP32 YAMNet"),
    ]
    for label, desc in eras:
        out.append(f"| {label} | {era_count.get(label, 0)} | {desc} |")
    out.append("")

    # Big-picture
    out.append("## Quick-action read-out")
    out.append("")
    out.append("Compact decision summary based on the numbers above:")
    out.append("")
    train_n = tier_total['high_pos'] + tier_total['high_neg']
    out.append(f"- **{train_n} training-eligible** captures, "
               f"{tier_total['high_pos']} cry / {tier_total['high_neg']} not-cry "
               f"(balance: {100*tier_total['high_pos']//max(train_n,1)}% / {100*tier_total['high_neg']//max(train_n,1)}%).")
    if train_n < 1000:
        out.append(f"- **Below the 1000-capture threshold** for first real training run "
                   f"(per `cry-detect-data-program-plan.md` §6.1).")
    if hp_clusters.get("screech", 0) < 10:
        out.append("- **Sub-type classifier deferred** — screech cluster too sparse.")
    if hn_speech / max(hn_speech + hn_other, 1) > 0.65:
        out.append("- **Negative class is environment-skewed** toward caregiver speech.")
    out.append("- **Embed-classifier (3rd ensemble oracle) is feasible** with current data — "
               "transfer learning from YAMNet embeddings on 250 samples.")
    out.append("")
    out.append("---")
    out.append("")
    out.append(f"*Refresh:* `tools/build_inventory.py` (or run after each "
               f"`tools/ensemble_audit.py` pass).*")

    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT.relative_to(REPO)} ({n} captures, "
          f"{tier_total['high_pos']} cry / {tier_total['high_neg']} not-cry training-eligible)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
